name: Build on release

on:
  release:
    types: [created]

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          # - target: universal-apple-darwin
          #   os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: rhodium
          target: ${{ matrix.target }}
          archive: rhodium-$tag-$target
          token: ${{ secrets.GITHUB_TOKEN }}
